/**:
  ros__parameters:
    object_detection:
      detection_model: 'CUSTOM_YOLOLIKE_BOX_OBJECTS'
      custom_onnx_file: '/home/cupcake/Desktop/deuterium/src/ros_controls/models/full_prequal.onnx'
      custom_onnx_input_size: 640 
      
      custom_class_count: 2

      class_0:
        label: 'gate'
        model_class_id: 0
        enabled: true
        confidence_threshold: 50.0
        is_grounded: false
        is_static: true

      class_1:
        label: 'pole'
        model_class_id: 1
        enabled: true
        confidence_threshold: 50.0
        is_grounded: false
        is_static: true
